### ISSUE TITLE
Test suite failure

### ISSUE THREAD

**Issue by snoyberg** [vincenthz/tasty-kat#1]
$ ./dist/build/test-tasty-kat/test-tasty-kat
test-tasty-kat: tests/KAT: openFile: does not exist (No such file or directory)

**Comment by peti** [comment]
We have the same error in NixOS: http://hydra.cryp.to/build/500640/nixlog/1/raw.

**Comment by vincenthz** [comment]
should be fixed. couple of days ago already, I forgot to report back
